spring.application.name=gateway
management.endpoints.web.exposure.include=health,info,mappings
info.app.name=gateway
info.app.version=0.0.1
spring.cloud.gateway.mvc.routes[0].id=api-status
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/status
spring.cloud.gateway.mvc.routes[0].filters[0]=SetPath=/status