spring.application.name=auth-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=catalog
spring.datasource.password=catalog
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration