services:
  postgres:
    image: postgres:16
    container_name: mini-market-postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      ports:
        "5432:5432"
      volumes:
        pgdata:/vae/lib/postresql/data
volumes:
  pgdata:
