services:
  postgres:
    image: postgres:16
    container_name: mini-market-postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_MULTIPLE_DATABASES:
        "auth,orders,payment"
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  pgdata:
