spring.application.name=order-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=catalog
spring.datasource.password=catalog
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
