INSERT INTO items (category, name, price, description, image_url, is_available)
VALUES
    ('BIRDS','Parrot Budgie',39.90,'Small friendly budgie, great for beginners.','https://placehold.co/600x400?text=Budgie',true),
    ('BIRDS','Canary Yellow',29.90,'Sings beautifully, Avoid drafts and cold air.','https://placehold.co/600x400?text=Canary',true),
    ('BIRDS','Finch Zebra',19.90,'Active zebra finch pair-friendly bird.','https://placehold.co/600x400?text=Zebra+Finch',true),
    ('BIRDS','Lovebird Peach-Faced',49.90,'Social lovebird, Needs attention and toys.','https://placehold.co/600x400?text=Lovebird',true),
    ('BIRDS','Cockatiel Grey',89.00,'Smart and affectionate cockatiel.','https://placehold.co/600x400?text=Cockatiel',true),
    ('MAMMALS','Hamster Syrian',14.90,'Low-maintenance pet, Mostly active at night.','https://placehold.co/600x400?text=Syrian+Hamster', true),
    ('MAMMALS','Guinea Pig',34.90,'Gentle guinea pig, Needs vitamin C in diet.','https://placehold.co/600x400?text=Guinea+Pig',true),
    ('MAMMALS','Rabbit Dwarf',79.00,'Dwarf rabbit, Needs space and daily interaction.','https://placehold.co/600x400?text=Dwarf+Rabbit',true),
    ('MAMMALS','Ferret',149.00,'Playful ferret, Requires supervision and enrichment.','https://placehold.co/600x400?text=Ferret',true),
    ('MAMMALS','Chinchilla',129.00,'Soft chinchilla, Needs dust baths and cool room.','https://placehold.co/600x400?text=Chinchilla',true),
    ('FISH','Goldfish',4.90,'Hardy goldfish, Needs filtered tank.','https://placehold.co/600x400?text=Goldfish',true),
    ('FISH','Neon Tetra',2.50,'Schooling fish, Keep 6+ for comfort.','https://placehold.co/600x400?text=Neon+Tetra',true),
    ('FISH','Betta Fish',14.90,'Colorful betta, Keep alone (territorial).','https://placehold.co/600x400?text=Betta',true),
    ('FISH','Guppy',3.50,'Easy livebearer, Great for community tanks.','https://placehold.co/600x400?text=Guppy',true),
    ('FISH','Corydoras Catfish',6.90,'Bottom-dweller, Keep in small group.','https://placehold.co/600x400?text=Corydoras',true),
    ('REPTILES','Leopard Gecko',89.00,'Nocturnal gecko, Simple heating and hides.','https://placehold.co/600x400?text=Leopard+Gecko',true),
    ('REPTILES','Corn Snake',99.00,'Docile snake, Great starter reptile.','https://placehold.co/600x400?text=Corn+Snake',true),
    ('REPTILES','Bearded Dragon',129.00,'Day-active lizard, Needs UVB lighting.','https://placehold.co/600x400?text=Bearded+Dragon',true),
    ('REPTILES','Red-Eared Slider Turtle',59.00,'Aquatic turtle, Needs basking spot and filter.','https://placehold.co/600x400?text=Red-Eared+Slider',true),
    ('REPTILES','Ball Python',149.00,'Calm python, Eats frozen/thawed prey.','https://placehold.co/600x400?text=Ball+Python',true),
    ('OTHER','Fish Food Premium 250g',7.90,'Complete flakes for tropical fish.','https://placehold.co/600x400?text=Fish+Food',true),
    ('OTHER','Reptile Heating Lamp 75W',19.90,'Heat lamp for terrariums, Use with thermostat.','https://placehold.co/600x400?text=Heating+Lamp',true),
    ('OTHER','Bird Cage Small',59.90,'Compact cage with perches and feeder cups.','https://placehold.co/600x400?text=Bird+Cage',true),
    ('OTHER','Aquarium Filter Mini',24.90,'Small internal filter for 20-40L tanks.','https://placehold.co/600x400?text=Aquarium+Filter',true),
    ('OTHER','Cat Toy Feather Wand',6.90,'Interactive toy for cats, supervised play.','https://placehold.co/600x400?text=Feather+Wand',true);